repos:
- repo: https://github.com/hakancelikdev/unimport
  rev: 0.8.3
  hooks:
    - id: unimport
      args: [-r]
-   repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--safe, --quiet]
- repo: https://github.com/dfm/black_nbconvert
  rev: v0.2.0
  hooks:
  - id: black_nbconvert
- repo: https://github.com/kynan/nbstripout
  rev: 0.3.9
  hooks:
    - id: nbstripout
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.9
  hooks:
    - id: nbqa-isort
      args: [--nbqa-mutate]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    -   id: flake8
        args: [--config=.flake8]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--errors-only]
